version: '3.7'

services:
  app:
    image: app
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - 'postgresql:host-gateway'
    ports:
      - 127.0.0.1:8001:8000